### ISSUE TITLE
privileged or cap SYS_ADMIN not required

### ISSUE THREAD

**Issue by nsymms** [j8r/dockerfiles#10]
FYI,

I'm able to run the container without any elevated privileges using this:

```
docker run -d --name systemd --tmpfs /tmp --tmpfs /run \
    --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    jrei/systemd-debian
```

Seems to be working OK, but maybe I missed something??

**Comment by j8r** [comment]
Thanks for the tip, it works for me too.
In the past, the command was with `-v /sys/fs/cgroup:/sys/fs/cgroup:ro`, but something has changed and it was no longer enough to have the container working.

For me, omitting `--tmpfs /tmp` works too (Ubuntu 20.04), can you confirm it too?

**Comment by nsymms** [comment]
On Debian 9.12, docker v19.03.11 if I omit `--tmpfs /run` I get the error:

```
Failed to mount tmpfs at /run: Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```
I get the same error on Debian 10 and Ubuntu 18.04 also.

I need to include both `--tmpfs /run` and `--tmpfs /run/lock` for it to work.

**Comment by j8r** [comment]
Thanks @nsymms! I updated the instructions.
