### ISSUE TITLE
MacOS BigSur Docker Volumes issue

### ISSUE THREAD

**Issue by Behner** [j8r/dockerfiles#11]
Seems there is an issue with Docker volumes syncing on MacOS Big Sur. I was able to resolve it by updating to the latest version of Docker Desktop Edge (Docker Desktop Community 2.5.1.0) and then running `apt-get update && apt-get dist-upgrade -y` on your 18.04 image. 

As soon as Docker releases their fixes to stable, I assume all that would be needed is an update to your image(s).

Thanks for the awesome images!

**Comment by j8r** [comment]
Sure, I can re-launch a build of the images, tell me!

**Comment by Behner** [comment]
I do not believe updating your images would negatively impact anyone. At your convenience, please update them.

Thank you!

**Comment by j8r** [comment]
I need to find a way to do it automatically... Maybe with GitHub Actions, with a CRON once per month.

**Comment by j8r** [comment]
CI to trigger image builds added https://github.com/j8r/dockerfiles/commit/48c46e5872d049f0f4c78afbd2d29ccdd953c389.
