### ISSUE TITLE
Using the images with docker compose doesn't work

### ISSUE THREAD

**Issue by makhatemakhate** [j8r/dockerfiles#12]
Tried to use jrei/systemd-centos:7 with docker compose but got the error "Failed to get D-Bus connection: Operation not permitted
"

**Comment by j8r** [comment]
Have you added the options described at https://github.com/j8r/dockerfiles/blob/master/systemd/centos/README.md?

**Comment by makhatemakhate** [comment]
> Have you added the options described at https://github.com/j8r/dockerfiles/blob/master/systemd/centos/README.md?

yah, the commands run well for a single container. But if I try to run a multi-container set up like [this](https://github.com/eRegister/bahmni_docker/blob/master/docker-compose.yml), it goes back to the same old error.

**Comment by makhatemakhate** [comment]
Got it! I used `privileged: true` and it worked!

**Comment by j8r** [comment]
Yes, `privileged` works. You can also try to add
```yml
tmpfs:
  - /run
  - /tmp
  - /run/lock
```
