### ISSUE TITLE
Multi-arch docker build

### ISSUE THREAD

**Issue by rnsc** [j8r/dockerfiles#20]
Hello,

First, thank you for your work.
I was wondering if it would be possible to add multi-arch support in those images?
I want to run them on ARM64 architecture.

Kind regards,

**Comment by j8r** [comment]
I won't be against.

**Comment by rnsc** [comment]
> I won't be against.

Cool!
I've looked at the GitHub workflows you already have, but I don't think I have experience with what you have setup there. I'd be willing to have a look, is there a documentation I could read to help you?

**Comment by j8r** [comment]
The GitHub Action is only there to trigger builds on Docker Hub. Last time I checked it didn't support building for aarch64/arm64.

The only solution I see is to build image in a GitHub Action, then push to Docker Hub. It is rather inconvenient.

**Comment by rnsc** [comment]
I'd be willing to create an updated GitHub workflow for this, can I submit a PR when I have some time for it?

**Comment by j8r** [comment]
You can. However, pushing to the docker registry won't work obviously (you will have to comment the line).

**Comment by rnsc** [comment]
@j8r PR created :)
